### PR TITLE
Make level is equal to the artifact level by default. (See more...)

### PR DESCRIPTION
**Pull request by rairulyle**
- Add Grade Score (Can you please check this one?)
- Make level is equal to the artifact level by default
- Fix output format
image

### CODE REVIEW

**Comment by rairulyle** [comment]
Add error handling for invalid image
image

**Comment by picklejason** [comment]
Hey, I looked at your code and also made some of my own changes and created another pull request #4. The default artifact level was nice and didn't seem to have any problems when I tested it. But your error handling had a lot of false positives, not sure the reason why so I didn't include it in the pull, the OCR parsed the images I tested fine but still threw an error.

**Comment by rairulyle** [comment]
@picklejason , saw it! Nice change! :)

I also commented.

**Comment by rairulyle** [comment]
Closed due to OP not accepting PR and PR branch was on master. 

Will submit a new one in a separate branch :)

**Pull request closed without merging**
