### PR TITLE
Use embed for message

### PR DESCRIPTION
**Pull request by picklejason**
## Additions/Changes to #3 
* Add embed message
    * shows level, formatted parsed stats, author of command (improve visibility on who called command if multiple/delays)
* Removed added error handling due to inconsistency
* Change naming of grade score (made it more of a general rating of the artifact rolls rather than classifying as poor/decent/excellent)

image

### CODE REVIEW

**Comment by rairulyle** [comment]
@picklejason , 

I like the embedded message! But it has some missing code, HP main stat is not being added in the `result_str` variable. Still, This is a plus on my fork! :D

But regarding the error handling, there were some images that don't work which is why I added the error handling. Maybe it's still good if we keep the error handling and just change the message? Try this image (Copy and Paste)
image

You also seem to disregard the error when the OCR failed. I added this now on my fork (Your PR + This)
image

**Comment by picklejason** [comment]
@Skullpluggery Thanks for the feedback! Yea I just tested that image and it threw an error (haha). I looked into the reason for it and I found that it could not parse the level for some reason and returned an empty list instead of the level so when it was casted into an int in the **rate** function it threw an TypeError. It makes sense why you added the error handling but it still had a lot of false positives on other images. So instead I did a quick fix/hack (probably will have other bugs) and set a default level of 20 when it can't parse the level properly. 
image
Also, thanks for catching my mistake on the error message, I forgot that I removed the send after I added the embed.

**Comment by rairulyle** [comment]
@picklejason ,

Yeah. It's weird that it can't parse that image lol. I might add that line of code to mine too!

Anyways, don't forget to add HP stat and values to result_str. Overall this is a good PR than mine, hope original author notice this!

**Comment by picklejason** [comment]
@Skullpluggery I tested the HP stat and it shows up in result_str but I only tested this image so I'm not sure if it works for all images, I will do some more bug testing later when I have time and will probably share the bot to some friends to help me find any more bugs.
image

**Comment by rairulyle** [comment]
@picklejason ,

I mean HP Main Stat artifacts like Flower (which has HP main stat as default). Try this image.
image

**Comment by picklejason** [comment]
@Skullpluggery Ahh thanks for telling me that 👍, I didn't manage to test everything yet. I hope the author sees the pull requests too, I feel like the embed messages provide much more clarity than the raw text. In the meantime I'll just use my separate instance of the bot and see what else I can add.

**Comment by rairulyle** [comment]
@picklejason , Yeah! Hopefully!

I made my bot more personal by implementing Paimon voice lines (kinda) HAHA!
image

**Comment by shrubin** [comment]
Thanks @picklejason and @Skullpluggery for the contributions, they look good! Just need to merge in some stuff and I'll move this over to master.

**Comment by rairulyle** [comment]
Anytime bro @shrubin , glad that you made this! 

Thanks also, @picklejason ! Cheers!

**Pull request merged**
